#!/usr/bin/env python3
"""Normalize and deduplicate scraped hackathon data for Supabase events table.

Input row shape (from current scrapers):
  - name
  - city
  - start_datetime
  - end_datetime
  - total_prize
  - website

Output row shape:
  - source
  - name
  - city
  - country
  - start_datetime_utc
  - end_datetime_utc
  - in_person
  - prize_pool
  - url

`id` is intentionally omitted because the Supabase table defines
`id bigint generated by default as identity`.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import re
import sys
import time
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse, urlunparse

import requests

DEFAULT_OUTPUT_FIELDS = [
    "source",
    "name",
    "city",
    "country",
    "start_datetime_utc",
    "end_datetime_utc",
    "in_person",
    "prize_pool",
    "url",
]

SPACE_RE = re.compile(r"\s+")
NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")
NUMBER_RE = re.compile(r"(?<!\d)(\d{1,3}(?:,\d{2,3})+|\d+(?:\.\d+)?)([kKmM]?)(?!\d)")
ONLINE_RE = re.compile(r"\b(online|virtual|remote|worldwide|global)\b", re.IGNORECASE)
LOCATION_SEGMENT_SPLIT_RE = re.compile(r"\s*(?:-|/|\||@|–|—)\s*")
TRAILING_NUMBER_RE = re.compile(r"\s+\d+[a-z]?$", re.IGNORECASE)
VENUE_HINT_RE = re.compile(
    r"\b(?:hall|center|centre|building|campus|auditorium|library|room|floor|"
    r"tower|lounge|ballroom|commons|lab|laboratory|office|university|college|"
    r"school|institute|academy)\b",
    re.IGNORECASE,
)
ADDRESS_HINT_RE = re.compile(
    r"\b(?:street|avenue|road|boulevard|lane|drive|suite)\b",
    re.IGNORECASE,
)
CITY_ABBREVIATIONS = {"SF", "NYC", "DC", "LA"}
CITY_NAME_EXCEPTIONS = {
    "state college",
    "college station",
    "college park",
    "university place",
}
STRICT_CITY_ADDRESS_KEYS = ("city", "town", "village", "municipality")
SECONDARY_CITY_ADDRESS_KEYS = ("hamlet",)
NOMINATIM_SEARCH_URL = "https://nominatim.openstreetmap.org/search"
LOOKUP_TOKEN_RE = re.compile(r"[A-Za-z0-9]+")
LOOKUP_STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "of",
    "in",
    "at",
    "on",
    "a",
    "an",
    "university",
    "college",
    "institute",
    "school",
    "hall",
    "center",
    "centre",
    "building",
    "campus",
    "auditorium",
    "library",
    "room",
    "floor",
    "tower",
    "lounge",
    "ballroom",
    "commons",
    "office",
    "student",
    "science",
    "engineering",
    "technology",
    "academy",
    "block",
    "lab",
}

# Currency detection patterns (mirrors scraper output formats).
SYMBOL_AMOUNT_RE = re.compile(
    r"(?P<symbol>[$€£₹¥])\s*"
    r"(?P<number>\d{1,3}(?:,\d{2,3})*(?:\.\d+)?|\d+(?:\.\d+)?)"
    r"\s*(?P<suffix>[kKmM])?"
)
CODE_AMOUNT_RE = re.compile(
    r"(?P<number>\d{1,3}(?:,\d{2,3})*(?:\.\d+)?|\d+(?:\.\d+)?)"
    r"\s*(?P<suffix>[kKmM])?\s*"
    r"(?P<code>USD|CAD|EUR|GBP|INR|AUD|JPY|PKR|MXN|SGD)\b",
    re.IGNORECASE,
)

SYMBOL_TO_CODE = {
    "$": "USD",
    "€": "EUR",
    "£": "GBP",
    "₹": "INR",
    "¥": "JPY",
}

# Approximate static exchange rates to USD (updated Feb 2026).
# These avoid an external API dependency; update periodically as needed.
CURRENCY_TO_USD: dict[str, float] = {
    "USD": 1.0,
    "CAD": 0.72,
    "EUR": 1.08,
    "GBP": 1.27,
    "INR": 0.012,
    "AUD": 0.65,
    "JPY": 0.0067,
    "PKR": 0.0036,
    "MXN": 0.058,
    "SGD": 0.74,
}

COUNTRY_ALIASES = {
    "US": "United States",
    "USA": "United States",
    "UNITED STATES": "United States",
    "UNITED STATES OF AMERICA": "United States",
    "UK": "United Kingdom",
    "U.K.": "United Kingdom",
    "UNITED KINGDOM": "United Kingdom",
    "ENGLAND": "United Kingdom",
    "SCOTLAND": "United Kingdom",
    "WALES": "United Kingdom",
    "IRELAND": "Ireland",
    "CANADA": "Canada",
    "CA": "Canada",
    "AU": "Australia",
    "AUS": "Australia",
    "AUSTRALIA": "Australia",
    "NZ": "New Zealand",
    "NEW ZEALAND": "New Zealand",
    "IN": "India",
    "INDIA": "India",
    "SG": "Singapore",
    "SINGAPORE": "Singapore",
    "MX": "Mexico",
    "MEXICO": "Mexico",
    "DE": "Germany",
    "GERMANY": "Germany",
    "FR": "France",
    "FRANCE": "France",
    "ES": "Spain",
    "SPAIN": "Spain",
    "JP": "Japan",
    "JAPAN": "Japan",
    "KR": "South Korea",
    "SOUTH KOREA": "South Korea",
    "CHINA": "China",
    "CN": "China",
    "BRAZIL": "Brazil",
    "BR": "Brazil",
}

US_STATE_CODES = {
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "DC",
}

US_STATE_NAMES = {
    "ALABAMA",
    "ALASKA",
    "ARIZONA",
    "ARKANSAS",
    "CALIFORNIA",
    "COLORADO",
    "CONNECTICUT",
    "DELAWARE",
    "FLORIDA",
    "GEORGIA",
    "HAWAII",
    "IDAHO",
    "ILLINOIS",
    "INDIANA",
    "IOWA",
    "KANSAS",
    "KENTUCKY",
    "LOUISIANA",
    "MAINE",
    "MARYLAND",
    "MASSACHUSETTS",
    "MICHIGAN",
    "MINNESOTA",
    "MISSISSIPPI",
    "MISSOURI",
    "MONTANA",
    "NEBRASKA",
    "NEVADA",
    "NEW HAMPSHIRE",
    "NEW JERSEY",
    "NEW MEXICO",
    "NEW YORK",
    "NORTH CAROLINA",
    "NORTH DAKOTA",
    "OHIO",
    "OKLAHOMA",
    "OREGON",
    "PENNSYLVANIA",
    "RHODE ISLAND",
    "SOUTH CAROLINA",
    "SOUTH DAKOTA",
    "TENNESSEE",
    "TEXAS",
    "UTAH",
    "VERMONT",
    "VIRGINIA",
    "WASHINGTON",
    "WEST VIRGINIA",
    "WISCONSIN",
    "WYOMING",
}


def log(message: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[{ts}] {message}")


def normalize_space(value: str | None) -> str | None:
    if value is None:
        return None
    cleaned = SPACE_RE.sub(" ", str(value)).strip()
    return cleaned or None


def normalize_url(value: str | None) -> str | None:
    text = normalize_space(value)
    if not text:
        return None

    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", text):
        text = f"https://{text}"

    parsed = urlparse(text)
    scheme = (parsed.scheme or "https").lower()
    host = (parsed.netloc or "").lower().strip()

    if not host and parsed.path:
        # Handles inputs like "example.com/path" after adding scheme.
        reparsed = urlparse(f"https://{text}")
        scheme = reparsed.scheme
        host = reparsed.netloc.lower().strip()
        path = reparsed.path
    else:
        path = parsed.path

    if host.startswith("www."):
        host = host[4:]

    if not host:
        return None

    clean_path = re.sub(r"/{2,}", "/", path or "/")
    if clean_path != "/":
        clean_path = clean_path.rstrip("/")
    return urlunparse((scheme, host, clean_path, "", "", ""))


def parse_isoish_datetime(value: Any) -> datetime | None:
    text = normalize_space(None if value is None else str(value))
    if not text:
        return None

    candidate = text.replace("Z", "+00:00")
    candidate = candidate.replace(" ", "T", 1) if "T" not in candidate and " " in candidate else candidate

    try:
        return datetime.fromisoformat(candidate)
    except ValueError:
        pass

    for fmt in (
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%m/%d/%Y %H:%M:%S",
    ):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue
    return None


def to_utc_timestamp(value: Any) -> str | None:
    dt = parse_isoish_datetime(value)
    if not dt:
        return None
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def parse_prize_pool(value: Any) -> int | None:
    """Extract the prize amount from a scraper total_prize string and convert to USD.

    Supports symbol-prefixed (e.g. ₹500,000) and code-suffixed (e.g. CAD 5,000)
    formats. Amounts without a recognized currency default to USD.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return int(round(float(value)))

    text = normalize_space(str(value))
    if not text:
        return None

    # Try to extract amounts with explicit currency info first.
    currency_amounts: list[tuple[str, float]] = []

    for match in SYMBOL_AMOUNT_RE.finditer(text):
        symbol = match.group("symbol")
        raw_number = float(match.group("number").replace(",", ""))
        suffix = (match.group("suffix") or "").lower()
        if suffix == "k":
            raw_number *= 1_000
        elif suffix == "m":
            raw_number *= 1_000_000
        code = SYMBOL_TO_CODE.get(symbol, "USD")
        currency_amounts.append((code, raw_number))

    for match in CODE_AMOUNT_RE.finditer(text):
        raw_number = float(match.group("number").replace(",", ""))
        suffix = (match.group("suffix") or "").lower()
        if suffix == "k":
            raw_number *= 1_000
        elif suffix == "m":
            raw_number *= 1_000_000
        code = match.group("code").upper()
        currency_amounts.append((code, raw_number))

    if currency_amounts:
        # Pick the largest amount (after USD conversion).
        best_usd = max(
            amount * CURRENCY_TO_USD.get(code, 1.0)
            for code, amount in currency_amounts
        )
        return int(round(best_usd))

    # Fallback: plain numbers without currency symbol (assume USD).
    amounts: list[float] = []
    for number, suffix in NUMBER_RE.findall(text):
        base = float(number.replace(",", ""))
        if suffix.lower() == "k":
            base *= 1_000
        elif suffix.lower() == "m":
            base *= 1_000_000
        amounts.append(base)

    if not amounts:
        return None
    return int(round(max(amounts)))


def normalize_name_key(name: str | None) -> str | None:
    text = normalize_space(name)
    if not text:
        return None
    lowered = text.casefold().replace("&", " and ")
    lowered = NON_ALNUM_RE.sub(" ", lowered).strip()
    if not lowered:
        return None
    tokens = [token for token in lowered.split() if token not in {"the", "a", "an"}]
    return " ".join(tokens) if tokens else None


def infer_country(parts: list[str]) -> str | None:
    if not parts:
        return None

    upper_parts = [part.strip().upper().rstrip(".") for part in parts if part.strip()]
    if not upper_parts:
        return None

    if any(token in US_STATE_CODES or token in US_STATE_NAMES for token in upper_parts[1:]):
        return "United States"

    last = upper_parts[-1]
    if last in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[last]

    if len(last) == 2 and last.isalpha() and last in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[last]

    return None


def is_region_token(part: str) -> bool:
    token = part.strip().upper().rstrip(".")
    if not token:
        return False
    return token in US_STATE_CODES or token in US_STATE_NAMES or token in COUNTRY_ALIASES


def is_likely_venue(part: str) -> bool:
    if not part:
        return False
    normalized = normalize_space(part)
    if normalized and normalized.casefold() in CITY_NAME_EXCEPTIONS:
        return False
    if ADDRESS_HINT_RE.search(part):
        return True
    lowered = part.casefold()
    if VENUE_HINT_RE.search(part):
        return True
    return " room " in f" {lowered} "


def is_city_like_name(part: str | None) -> bool:
    city = normalize_space(part)
    if not city:
        return False

    lowered = city.casefold()
    if lowered in {"online", "unknown"}:
        return True
    if lowered in CITY_NAME_EXCEPTIONS:
        return True

    if is_short_upper_code(city):
        return False
    if is_likely_venue(city):
        return False
    if ADDRESS_HINT_RE.search(city):
        return False
    if re.search(r"\d", city):
        return False

    tokens = [token for token in LOOKUP_TOKEN_RE.findall(city) if token]
    if not tokens:
        return False
    if all(token.casefold() in LOOKUP_STOPWORDS for token in tokens):
        return False
    return True


def normalize_location_candidate(part: str) -> str | None:
    cleaned = normalize_space(part.strip(" -"))
    if not cleaned:
        return None
    trimmed = normalize_space(TRAILING_NUMBER_RE.sub("", cleaned)) or cleaned
    return trimmed


def is_short_upper_code(part: str) -> bool:
    letters_only = re.sub(r"[^A-Za-z]", "", part)
    if not letters_only:
        return False
    if letters_only.upper() in CITY_ABBREVIATIONS:
        return False
    return letters_only.isupper() and len(letters_only) <= 5


def extract_city_from_fragment(fragment: str) -> str | None:
    base = normalize_space(fragment)
    if not base:
        return None

    split_tokens = [normalize_space(token) for token in LOCATION_SEGMENT_SPLIT_RE.split(base)]
    split_tokens = [token for token in split_tokens if token]
    if len(split_tokens) > 1:
        for token in reversed(split_tokens):
            candidate = normalize_location_candidate(token)
            if not candidate:
                continue
            if is_region_token(candidate) or is_likely_venue(candidate) or is_short_upper_code(candidate):
                continue
            return candidate

    candidate = normalize_location_candidate(base)
    if not candidate:
        return None
    if is_region_token(candidate) or is_likely_venue(candidate) or is_short_upper_code(candidate):
        return None
    return candidate


def choose_city_from_parts(parts: list[str]) -> str | None:
    if not parts:
        return None

    trimmed_parts = list(parts)
    while trimmed_parts and is_region_token(trimmed_parts[-1]):
        trimmed_parts.pop()
    if not trimmed_parts:
        return None

    for part in reversed(trimmed_parts):
        candidate = extract_city_from_fragment(part)
        if candidate:
            return candidate

    return extract_city_from_fragment(trimmed_parts[0])


def parse_city_country_in_person(raw_city: str | None) -> tuple[str | None, str | None, bool | None]:
    city_text = normalize_space(raw_city)
    if not city_text:
        return None, None, None

    if ONLINE_RE.search(city_text):
        return None, None, False

    parts = [normalize_space(part.strip(" -")) for part in city_text.split(",")]
    parts = [part for part in parts if part]
    if not parts:
        return None, None, None

    country = infer_country(parts)
    city = choose_city_from_parts(parts)

    if len(parts) == 1:
        token = parts[0].upper().rstrip(".")
        if token in COUNTRY_ALIASES:
            return None, COUNTRY_ALIASES[token], None

    if city and not is_city_like_name(city):
        city = None

    return city, country, True


def default_city_lookup_cache_path() -> Path:
    return Path(__file__).resolve().parents[2] / "data" / "location_city_cache.json"


def load_city_lookup_cache(path: Path) -> dict[str, dict[str, str | None]]:
    if not path.exists():
        return {}

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}

    if not isinstance(payload, dict):
        return {}

    cache: dict[str, dict[str, str | None]] = {}
    for key, value in payload.items():
        if not isinstance(key, str) or not isinstance(value, dict):
            continue
        city = normalize_space(value.get("city"))
        country = normalize_space(value.get("country"))
        if city and not is_city_like_name(city):
            city = None
        cache[key] = {"city": city, "country": country}
    return cache


def save_city_lookup_cache(path: Path, cache: dict[str, dict[str, str | None]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = {
        key: {"city": value.get("city"), "country": value.get("country")}
        for key, value in sorted(cache.items())
    }
    path.write_text(json.dumps(serialized, indent=2, ensure_ascii=False), encoding="utf-8")


def build_city_lookup_cache_key(raw_location: str, url: str | None) -> str:
    host = urlparse(url).netloc.casefold().strip() if url else ""
    return f"{raw_location.casefold()}|{host}"


def build_city_lookup_queries(raw_location: str, event_name: str | None) -> list[str]:
    base = normalize_space(html.unescape(raw_location))
    if not base:
        return []

    queries: list[str] = []
    seen: set[str] = set()

    def add(candidate: str | None) -> None:
        cleaned = normalize_space(candidate)
        if not cleaned:
            return
        key = cleaned.casefold()
        if key in seen:
            return
        seen.add(key)
        queries.append(cleaned)

    add(base)

    comma_parts = [normalize_space(part.strip(" -")) for part in base.split(",")]
    comma_parts = [part for part in comma_parts if part]
    if len(comma_parts) > 1:
        add(", ".join(comma_parts[:-1]))
        add(", ".join(comma_parts[:2]))
        add(comma_parts[0])
        add(comma_parts[-2])

    split_parts = [normalize_space(part) for part in LOCATION_SEGMENT_SPLIT_RE.split(base)]
    split_parts = [part for part in split_parts if part]
    if len(split_parts) > 1:
        add(", ".join(split_parts[:-1]))
        add(split_parts[0])
        for part in split_parts:
            if not is_likely_venue(part) and not is_short_upper_code(part):
                add(part)

    if event_name:
        primary = split_parts[0] if split_parts else base
        add(f"{event_name} {primary}")

    return queries[:6]


def extract_lookup_tokens(query: str) -> list[str]:
    tokens: list[str] = []
    seen: set[str] = set()
    for token in LOOKUP_TOKEN_RE.findall(query):
        if token.isdigit():
            continue
        lowered = token.casefold()
        if lowered in LOOKUP_STOPWORDS:
            continue
        if len(token) >= 4 or (token.isupper() and 2 <= len(token) <= 5):
            if lowered not in seen:
                seen.add(lowered)
                tokens.append(lowered)
    return tokens


def extract_city_country_from_lookup_result(result: dict[str, Any]) -> tuple[str | None, str | None]:
    address = result.get("address")
    if not isinstance(address, dict):
        return None, None

    city = None
    for key in STRICT_CITY_ADDRESS_KEYS:
        candidate = normalize_space(address.get(key))
        if candidate and is_city_like_name(candidate):
            city = candidate
            break

    if city is None:
        # Limited fallback for locales where "hamlet" is the closest city-level value.
        for key in SECONDARY_CITY_ADDRESS_KEYS:
            candidate = normalize_space(address.get(key))
            if candidate and is_city_like_name(candidate):
                city = candidate
                break

    country = normalize_space(address.get("country"))
    return city, country


def score_lookup_result(result: dict[str, Any], tokens: list[str]) -> tuple[int, float]:
    display_name = normalize_space(result.get("display_name")) or ""
    lowered = display_name.casefold()
    token_hits = sum(1 for token in tokens if token in lowered)

    importance_raw = result.get("importance")
    try:
        importance = float(importance_raw)
    except (TypeError, ValueError):
        importance = 0.0

    return token_hits, importance


def resolve_city_with_online_lookup(
    *,
    raw_location: str,
    event_name: str | None,
    url: str | None,
    country_hint: str | None,
    session: requests.Session,
    cache: dict[str, dict[str, str | None]],
    timeout_seconds: float,
    min_request_interval_seconds: float,
    last_request_at: list[float],
) -> tuple[str | None, str | None, bool]:
    cache_key = build_city_lookup_cache_key(raw_location, url)
    cached = cache.get(cache_key)
    if cached is not None:
        return cached.get("city"), cached.get("country"), True

    queries = build_city_lookup_queries(raw_location, event_name)
    country_hint_normalized = normalize_space(country_hint)
    country_hint_token = country_hint_normalized.casefold() if country_hint_normalized else None

    for query in queries:
        elapsed = time.monotonic() - last_request_at[0]
        wait_seconds = min_request_interval_seconds - elapsed
        if wait_seconds > 0:
            time.sleep(wait_seconds)

        try:
            response = session.get(
                NOMINATIM_SEARCH_URL,
                params={"q": query, "format": "jsonv2", "limit": 5, "addressdetails": 1},
                timeout=timeout_seconds,
            )
            last_request_at[0] = time.monotonic()
            response.raise_for_status()
            payload = response.json()
        except (requests.RequestException, ValueError):
            continue

        if not isinstance(payload, list):
            continue

        tokens = extract_lookup_tokens(query)
        best: tuple[tuple[int, float], str, str | None] | None = None
        for item in payload:
            if not isinstance(item, dict):
                continue
            city, country = extract_city_country_from_lookup_result(item)
            if not city:
                continue

            token_hits, importance = score_lookup_result(item, tokens)
            if tokens and token_hits == 0:
                continue

            if country_hint_token and country:
                country_token = country.casefold()
                if country_hint_token not in country_token and country_token not in country_hint_token:
                    importance -= 1.0

            rank = (token_hits, importance)
            if best is None or rank > best[0]:
                best = (rank, city, country)

        if best is not None:
            _, city, country = best
            cache[cache_key] = {"city": city, "country": country}
            return city, country, False

    cache[cache_key] = {"city": None, "country": None}
    return None, None, False


def fallback_city_from_raw_location(raw_location: str) -> str:
    candidate = normalize_space(raw_location) or "Unknown"
    if is_likely_venue(candidate) or is_short_upper_code(candidate):
        return "Unknown"
    return candidate


def enrich_missing_cities(
    records: list[dict[str, Any]],
    *,
    enable_online_lookup: bool,
    cache: dict[str, dict[str, str | None]],
    timeout_seconds: float,
    min_request_interval_seconds: float,
) -> dict[str, int]:
    stats = {
        "resolved_online": 0,
        "cache_hits": 0,
        "fallback_raw_location": 0,
        "set_online_label": 0,
        "set_unknown": 0,
    }

    session: requests.Session | None = None
    last_request_at = [0.0]

    if enable_online_lookup:
        session = requests.Session()
        session.headers.update(
            {
                "User-Agent": (
                    "Irvine-Hacks-City-Resolver/1.0 "
                    "(https://github.com/joshuadowd/Irvine-Hacks)"
                )
            }
        )

    try:
        for record in records:
            existing_city = normalize_space(record.get("city"))
            if existing_city and is_city_like_name(existing_city):
                continue
            if existing_city and not is_city_like_name(existing_city):
                record["city"] = None

            if record.get("in_person") is False:
                record["city"] = "Online"
                stats["set_online_label"] += 1
                continue

            raw_location = normalize_space(html.unescape(str(record.get("_raw_city") or "")))
            if not raw_location:
                record["city"] = "Unknown"
                stats["set_unknown"] += 1
                continue

            if enable_online_lookup and session is not None:
                resolved_city, resolved_country, from_cache = resolve_city_with_online_lookup(
                    raw_location=raw_location,
                    event_name=normalize_space(record.get("name")),
                    url=normalize_url(record.get("url")),
                    country_hint=normalize_space(record.get("country")),
                    session=session,
                    cache=cache,
                    timeout_seconds=timeout_seconds,
                    min_request_interval_seconds=min_request_interval_seconds,
                    last_request_at=last_request_at,
                )
                if from_cache:
                    stats["cache_hits"] += 1
                if resolved_city:
                    record["city"] = resolved_city
                    if not record.get("country") and resolved_country:
                        record["country"] = resolved_country
                    stats["resolved_online"] += 1
                    continue

            fallback_city = fallback_city_from_raw_location(raw_location)
            record["city"] = fallback_city
            if fallback_city == "Unknown":
                stats["set_unknown"] += 1
            else:
                stats["fallback_raw_location"] += 1
    finally:
        if session is not None:
            session.close()

    return stats


def choose_text(preferred: str | None, candidate: str | None) -> str | None:
    if not preferred:
        return candidate
    if not candidate:
        return preferred
    return candidate if len(candidate) > len(preferred) else preferred


def parse_output_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        return None


def has_precise_start_time(value: str | None) -> bool:
    dt = parse_output_datetime(value)
    if not dt:
        return False
    return dt.time().isoformat() != "00:00:00"


def has_precise_end_time(value: str | None) -> bool:
    dt = parse_output_datetime(value)
    if not dt:
        return False
    return dt.time().isoformat() != "23:59:59"


def choose_start_datetime(left: str | None, right: str | None) -> str | None:
    if not left:
        return right
    if not right:
        return left

    left_precise = has_precise_start_time(left)
    right_precise = has_precise_start_time(right)
    if left_precise != right_precise:
        return right if right_precise else left

    left_dt = parse_output_datetime(left)
    right_dt = parse_output_datetime(right)
    if left_dt and right_dt:
        return left if left_dt <= right_dt else right
    return choose_text(left, right)


def choose_end_datetime(left: str | None, right: str | None) -> str | None:
    if not left:
        return right
    if not right:
        return left

    left_precise = has_precise_end_time(left)
    right_precise = has_precise_end_time(right)
    if left_precise != right_precise:
        return right if right_precise else left

    left_dt = parse_output_datetime(left)
    right_dt = parse_output_datetime(right)
    if left_dt and right_dt:
        return left if left_dt >= right_dt else right
    return choose_text(left, right)


def choose_in_person(left: bool | None, right: bool | None) -> bool | None:
    values = [value for value in (left, right) if value is not None]
    if not values:
        return None
    if all(value == values[0] for value in values):
        return values[0]
    return None


def url_rank(url: str | None) -> tuple[int, int]:
    if not url:
        return (-10, 0)
    host = urlparse(url).netloc
    rank = 0
    if "devpost.com" in host:
        rank -= 2
    if "devfolio.co" in host:
        rank -= 2
    if "mlh" in host:
        rank -= 1
    if urlparse(url).path not in {"", "/"}:
        rank += 1
    return (rank, len(url))


def merge_records(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    merged = dict(left)

    merged["name"] = choose_text(left.get("name"), right.get("name"))
    merged["city"] = choose_text(left.get("city"), right.get("city"))
    merged["_raw_city"] = choose_text(left.get("_raw_city"), right.get("_raw_city"))
    merged["country"] = choose_text(left.get("country"), right.get("country"))
    merged["start_datetime_utc"] = choose_start_datetime(
        left.get("start_datetime_utc"), right.get("start_datetime_utc")
    )
    merged["end_datetime_utc"] = choose_end_datetime(
        left.get("end_datetime_utc"), right.get("end_datetime_utc")
    )
    merged["in_person"] = choose_in_person(left.get("in_person"), right.get("in_person"))

    left_prize = left.get("prize_pool")
    right_prize = right.get("prize_pool")
    if left_prize is None:
        merged["prize_pool"] = right_prize
    elif right_prize is None:
        merged["prize_pool"] = left_prize
    else:
        merged["prize_pool"] = max(int(left_prize), int(right_prize))

    left_url = left.get("url")
    right_url = right.get("url")
    merged["url"] = right_url if url_rank(right_url) > url_rank(left_url) else left_url

    sources = set(left.get("_sources", set()))
    sources.update(right.get("_sources", set()))
    merged["_sources"] = sources
    merged["source"] = ",".join(sorted(sources)) if sources else (left.get("source") or right.get("source") or "mlh")
    return merged


def normalize_scraped_row(row: dict[str, Any], source: str) -> dict[str, Any] | None:
    name = normalize_space(row.get("name"))
    raw_city = normalize_space(html.unescape(str(row.get("city") or "")))
    start_raw = row.get("start_datetime", row.get("start_datetime_utc"))
    end_raw = row.get("end_datetime", row.get("end_datetime_utc"))
    prize_raw = row.get("total_prize", row.get("prize_pool"))
    url_raw = row.get("website", row.get("url"))

    url = normalize_url(url_raw)
    if not name and not url:
        return None

    city, country, in_person = parse_city_country_in_person(raw_city)
    if city and not is_city_like_name(city):
        city = None

    normalized: dict[str, Any] = {
        "source": source,
        "name": name,
        "city": city,
        "_raw_city": raw_city,
        "country": country,
        "start_datetime_utc": to_utc_timestamp(start_raw),
        "end_datetime_utc": to_utc_timestamp(end_raw),
        "in_person": in_person,
        "prize_pool": parse_prize_pool(prize_raw),
        "url": url,
        "_sources": {source},
    }

    if normalized["start_datetime_utc"] and normalized["end_datetime_utc"]:
        start_dt = parse_output_datetime(normalized["start_datetime_utc"])
        end_dt = parse_output_datetime(normalized["end_datetime_utc"])
        if start_dt and end_dt and end_dt < start_dt:
            normalized["start_datetime_utc"], normalized["end_datetime_utc"] = (
                normalized["end_datetime_utc"],
                normalized["start_datetime_utc"],
            )

    return normalized


def read_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    suffix = path.suffix.lower()
    if suffix == ".json":
        with path.open("r", encoding="utf-8") as fh:
            payload = json.load(fh)
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, dict)]
        if isinstance(payload, dict):
            for key in ("records", "events", "hackathons", "data"):
                value = payload.get(key)
                if isinstance(value, list):
                    return [item for item in value if isinstance(item, dict)]
            return [payload]
        raise ValueError(f"Unsupported JSON payload in {path}")

    if suffix == ".csv":
        with path.open("r", encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            return [dict(row) for row in reader]

    raise ValueError(f"Unsupported file extension for {path}")


def load_normalized_records(paths: list[Path], source: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in paths:
        for row in read_rows(path):
            normalized = normalize_scraped_row(row, source)
            if normalized:
                records.append(normalized)
    return records


def merge_by_url(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: "OrderedDict[str, dict[str, Any]]" = OrderedDict()
    passthrough: list[dict[str, Any]] = []

    for record in records:
        key = record.get("url")
        if not key:
            passthrough.append(record)
            continue
        if key in grouped:
            grouped[key] = merge_records(grouped[key], record)
        else:
            grouped[key] = record

    return list(grouped.values()) + passthrough


def merge_by_name_start(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: "OrderedDict[tuple[str, str], dict[str, Any]]" = OrderedDict()
    passthrough: list[dict[str, Any]] = []

    for record in records:
        name_key = normalize_name_key(record.get("name"))
        start = record.get("start_datetime_utc")
        start_date = start[:10] if isinstance(start, str) and len(start) >= 10 else None
        if not name_key or not start_date:
            passthrough.append(record)
            continue

        key = (name_key, start_date)
        if key in grouped:
            grouped[key] = merge_records(grouped[key], record)
        else:
            grouped[key] = record

    return list(grouped.values()) + passthrough


def strip_internal_fields(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for record in records:
        if record.get("in_person") is False:
            continue
        cleaned.append({field: record.get(field) for field in DEFAULT_OUTPUT_FIELDS})
    return cleaned


def infer_output_format(output_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    return "csv" if output_path.suffix.lower() == ".csv" else "json"


def write_output(records: list[dict[str, Any]], output_path: Path, output_format: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_format == "json":
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(records, fh, indent=2, ensure_ascii=False)
        return

    if output_format == "csv":
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=DEFAULT_OUTPUT_FIELDS)
            writer.writeheader()
            writer.writerows(records)
        return

    raise ValueError(f"Unsupported output format: {output_format}")


def discover_default_inputs(repo_root: Path) -> tuple[list[Path], list[Path], list[Path]]:
    mlh_patterns = [
        "MLH-Scraper/mlh*.json",
        "MLH-Scraper/mlh*.csv",
        "mlh*.json",
        "mlh*.csv",
    ]
    devpost_patterns = [
        "Devpost-Scraper/devpost*.json",
        "Devpost-Scraper/devpost*.csv",
        "devpost*.json",
        "devpost*.csv",
    ]
    devfolio_patterns = [
        "Devfolio-Scraper/devfolio*.json",
        "Devfolio-Scraper/devfolio*.csv",
        "devfolio*.json",
        "devfolio*.csv",
    ]

    mlh_files: list[Path] = []
    devpost_files: list[Path] = []
    devfolio_files: list[Path] = []

    for pattern in mlh_patterns:
        mlh_files.extend(sorted(repo_root.glob(pattern)))
    for pattern in devpost_patterns:
        devpost_files.extend(sorted(repo_root.glob(pattern)))
    for pattern in devfolio_patterns:
        devfolio_files.extend(sorted(repo_root.glob(pattern)))

    # Preserve order while removing duplicates.
    mlh_unique = list(dict.fromkeys(path.resolve() for path in mlh_files))
    devpost_unique = list(dict.fromkeys(path.resolve() for path in devpost_files))
    devfolio_unique = list(dict.fromkeys(path.resolve() for path in devfolio_files))
    return mlh_unique, devpost_unique, devfolio_unique


def parse_args(argv: list[str]) -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Clean MLH/Devpost/Devfolio scraped data for Supabase events ingestion."
    )
    parser.add_argument("--mlh", nargs="*", default=None, help="MLH input files (JSON or CSV)")
    parser.add_argument("--devpost", nargs="*", default=None, help="Devpost input files (JSON or CSV)")
    parser.add_argument("--devfolio", nargs="*", default=None, help="Devfolio input files (JSON or CSV)")
    parser.add_argument(
        "--output",
        default=str(script_dir / "cleaned_events.json"),
        help="Output file path (JSON or CSV)",
    )
    parser.add_argument("--format", choices=("json", "csv"), default=None, help="Output format override")
    parser.add_argument(
        "--disable-online-city-lookup",
        action="store_true",
        help="Disable online lookup fallback for unresolved city values.",
    )
    parser.add_argument(
        "--city-lookup-cache",
        default=str(default_city_lookup_cache_path()),
        help="Path to JSON cache for online city lookup results.",
    )
    parser.add_argument(
        "--city-lookup-timeout",
        type=float,
        default=15.0,
        help="HTTP timeout in seconds for online city lookups.",
    )
    parser.add_argument(
        "--city-lookup-rate-limit",
        type=float,
        default=1.0,
        help="Minimum seconds between online city-lookup requests.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    output_path = Path(args.output).expanduser().resolve()
    log(f"Starting events.py formatter (output={output_path})")

    enable_online_city_lookup = not args.disable_online_city_lookup
    city_lookup_cache_path = Path(args.city_lookup_cache).expanduser().resolve()
    city_lookup_timeout = max(1.0, args.city_lookup_timeout)
    city_lookup_rate_limit = max(0.0, args.city_lookup_rate_limit)
    city_lookup_cache = load_city_lookup_cache(city_lookup_cache_path) if enable_online_city_lookup else {}
    if enable_online_city_lookup:
        log(
            "Online city lookup enabled: "
            f"cache={city_lookup_cache_path}, cached_keys={len(city_lookup_cache)}, "
            f"timeout={city_lookup_timeout}s, min_interval={city_lookup_rate_limit}s"
        )
    else:
        log("Online city lookup disabled; unresolved city values will fallback to raw location text.")

    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent

    if args.mlh is None and args.devpost is None and args.devfolio is None:
        mlh_files, devpost_files, devfolio_files = discover_default_inputs(repo_root)
        log(
            "Auto-discovered input files: "
            f"mlh={len(mlh_files)}, devpost={len(devpost_files)}, devfolio={len(devfolio_files)}"
        )
    else:
        mlh_files = [Path(path).expanduser().resolve() for path in (args.mlh or [])]
        devpost_files = [Path(path).expanduser().resolve() for path in (args.devpost or [])]
        devfolio_files = [Path(path).expanduser().resolve() for path in (args.devfolio or [])]
        log(
            "Using explicit input files: "
            f"mlh={len(mlh_files)}, devpost={len(devpost_files)}, devfolio={len(devfolio_files)}"
        )

    if not mlh_files and not devpost_files and not devfolio_files:
        print(
            (
                "No input files found. Provide --mlh/--devpost/--devfolio paths or place scraper outputs "
                "in MLH-Scraper/, Devpost-Scraper/, and Devfolio-Scraper/."
            ),
            file=sys.stderr,
        )
        return 2

    try:
        mlh_records = load_normalized_records(mlh_files, "mlh")
        devpost_records = load_normalized_records(devpost_files, "devpost")
        devfolio_records = load_normalized_records(devfolio_files, "devfolio")
        records = mlh_records + devpost_records + devfolio_records
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as exc:
        print(f"Failed to read input files: {exc}", file=sys.stderr)
        return 1

    log(
        "Loaded normalized records: "
        f"mlh={len(mlh_records)}, devpost={len(devpost_records)}, devfolio={len(devfolio_records)}, total={len(records)}"
    )

    if not records:
        print("No valid records found in input files.", file=sys.stderr)
        return 1

    pre_dedupe_count = len(records)
    merged = merge_by_url(records)
    merged = merge_by_name_start(merged)
    log(f"Merged records after dedupe: {len(merged)} (from {pre_dedupe_count})")

    city_stats = enrich_missing_cities(
        merged,
        enable_online_lookup=enable_online_city_lookup,
        cache=city_lookup_cache,
        timeout_seconds=city_lookup_timeout,
        min_request_interval_seconds=city_lookup_rate_limit,
    )
    if enable_online_city_lookup:
        save_city_lookup_cache(city_lookup_cache_path, city_lookup_cache)
    log(
        "City enrichment results: "
        f"resolved_online={city_stats['resolved_online']}, "
        f"cache_hits={city_stats['cache_hits']}, "
        f"fallback_raw_location={city_stats['fallback_raw_location']}, "
        f"set_online_label={city_stats['set_online_label']}, "
        f"set_unknown={city_stats['set_unknown']}"
    )

    merged.sort(key=lambda row: ((row.get("start_datetime_utc") or ""), (row.get("name") or "").casefold()))
    cleaned = strip_internal_fields(merged)
    log(f"Final cleaned records (in-person only): {len(cleaned)}")

    output_format = infer_output_format(output_path, args.format)
    write_output(cleaned, output_path, output_format)

    print(
        f"Wrote {len(cleaned)} cleaned events to {output_path} "
        f"(from {len(records)} raw rows, removed {len(records) - len(cleaned)} duplicates)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
