#!/usr/bin/env python3
"""Format US city hotel average-price CSV into rows for public.lodging.

Target schema:
  id bigint generated by default as identity not null,
  city text,
  nightly_rate real

Input CSV columns: city_name, average_price

By default, this script outputs only `city` + `nightly_rate` because `id` is
identity-generated by Postgres. Use --include-id if you want deterministic ids
in output files.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def log(message: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[{ts}] {message}")


def open_csv_with_fallback(path: Path) -> tuple[csv.DictReader, Any]:
    encodings = ("utf-8-sig", "utf-8", "cp1252", "latin-1")
    last_error: Exception | None = None

    for encoding in encodings:
        try:
            fh = path.open("r", encoding=encoding, newline="")
            reader = csv.DictReader(fh)
            # Force header decode/read now.
            _ = reader.fieldnames
            return reader, fh
        except Exception as exc:
            last_error = exc
            try:
                fh.close()  # type: ignore[name-defined]
            except Exception:
                pass

    raise ValueError(f"Could not read CSV {path}: {last_error}")


def read_hotel_prices(path: Path) -> list[tuple[str, float]]:
    """Read the us_city_hotel_average_prices.csv file.

    Expected columns: city_name, average_price
    Returns a list of (city, nightly_rate) tuples.
    """
    reader, fh = open_csv_with_fallback(path)
    rows: list[tuple[str, float]] = []
    skipped = 0

    try:
        for row in reader:
            city = (row.get("city_name") or "").strip()
            price_raw = (row.get("average_price") or "").strip()
            if not city or not price_raw:
                skipped += 1
                continue
            try:
                nightly_rate = round(float(price_raw), 2)
            except ValueError:
                skipped += 1
                continue
            rows.append((city, nightly_rate))
    finally:
        fh.close()

    log(f"Read {len(rows)} rows from {path.name} (skipped {skipped})")
    return rows


def write_output(
    rows: list[tuple[str, float]],
    output_path: Path,
    output_format: str,
    include_id: bool,
    id_start: int,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if include_id:
        fields = ["id", "city", "nightly_rate"]
    else:
        fields = ["city", "nightly_rate"]

    records: list[dict[str, Any]] = []
    for idx, (city, nightly_rate) in enumerate(rows, start=id_start):
        record: dict[str, Any] = {"city": city, "nightly_rate": nightly_rate}
        if include_id:
            record["id"] = idx
        records.append(record)

    if output_format == "json":
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(records, fh, indent=2, ensure_ascii=False)
        return

    if output_format == "csv":
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fields)
            writer.writeheader()
            writer.writerows(records)
        return

    raise ValueError(f"Unsupported output format: {output_format}")


def infer_output_format(output_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    if output_path.suffix.lower() == ".json":
        return "json"
    return "csv"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Format US city hotel average prices into lodging rows (city, nightly_rate)."
    )
    parser.add_argument("--input", required=True, help="Path to us_city_hotel_average_prices.csv")
    parser.add_argument("--output", required=True, help="Output file path (.csv or .json)")
    parser.add_argument("--format", choices=("csv", "json"), default=None, help="Output format override")
    parser.add_argument("--include-id", action="store_true", help="Include deterministic id column")
    parser.add_argument("--id-start", type=int, default=1, help="Starting id when --include-id is used")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    log(f"Starting lodging formatter (input={input_path}, output={output_path})")

    if not input_path.exists():
        print(f"Input file not found: {input_path}", file=sys.stderr)
        return 2

    try:
        rows = read_hotel_prices(input_path)
    except Exception as exc:
        print(f"Failed reading input file: {exc}", file=sys.stderr)
        return 1

    if not rows:
        print("No lodging rows generated.", file=sys.stderr)
        return 1

    # Sort by city name for consistent output
    rows.sort(key=lambda r: r[0].casefold())

    try:
        output_format = infer_output_format(output_path, args.format)
        write_output(
            rows=rows,
            output_path=output_path,
            output_format=output_format,
            include_id=args.include_id,
            id_start=args.id_start,
        )
    except Exception as exc:
        print(f"Failed writing output: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {len(rows)} lodging rows to {output_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
