#!/usr/bin/env python3
"""Format hotel average-price CSV into rows for public.lodging.

Target schema:
  id bigint generated by default as identity not null,
  city text,
  nightly_rate real

Input CSV columns (flexible):
  - Preferred: city_name (or city), average_price
  - Also supported: airport_code (or iata/iata_code/destination_airport), average_price
    when --airport-city-map is supplied or airport code is in built-in defaults.

By default, this script outputs only `city` + `nightly_rate` because `id` is
identity-generated by Postgres. Use --include-id if you want deterministic ids
in output files.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PRICE_RE = re.compile(r"-?\d+(?:,\d{3})*(?:\.\d+)?")

# Canonical city labels used when airport-code-only rows are provided.
DEFAULT_AIRPORT_TO_CITY: dict[str, str] = {
    "ATL": "Atlanta",
    "AUS": "Austin",
    "BNA": "Nashville",
    "BOS": "Boston",
    "BWI": "Baltimore",
    "CLE": "Cleveland",
    "CLT": "Charlotte",
    "CMH": "Columbus",
    "CMI": "Champaign",
    "DCA": "Washington",
    "DEN": "Denver",
    "DFW": "Dallas",
    "DTW": "Detroit",
    "EWR": "Newark",
    "GNV": "Gainesville",
    "IAH": "Houston",
    "ITH": "Ithaca",
    "JFK": "New York",
    "LAS": "Las Vegas",
    "LAX": "Los Angeles",
    "MCI": "Kansas City",
    "MCO": "Orlando",
    "MIA": "Miami",
    "MSP": "Minneapolis",
    "OAK": "Oakland",
    "ORD": "Chicago",
    "PDX": "Portland",
    "PHL": "Philadelphia",
    "PHX": "Phoenix",
    "PIT": "Pittsburgh",
    "RDU": "Raleigh",
    "SAN": "San Diego",
    "SAT": "San Antonio",
    "SEA": "Seattle",
    "SFO": "San Francisco",
    "SJC": "San Jose",
    "SLC": "Salt Lake City",
    "SNA": "Irvine",
    "STL": "St. Louis",
}

CITY_COLUMNS = ("city_name", "city", "destination_city")
PRICE_COLUMNS = ("average_price", "nightly_rate", "price")
AIRPORT_COLUMNS = ("airport_code", "destination_airport", "iata", "iata_code", "airport")


def log(message: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[{ts}] {message}")


def open_csv_with_fallback(path: Path) -> tuple[csv.DictReader, Any]:
    encodings = ("utf-8-sig", "utf-8", "cp1252", "latin-1")
    last_error: Exception | None = None

    for encoding in encodings:
        try:
            fh = path.open("r", encoding=encoding, newline="")
            reader = csv.DictReader(fh)
            # Force header decode/read now.
            _ = reader.fieldnames
            return reader, fh
        except Exception as exc:
            last_error = exc
            try:
                fh.close()  # type: ignore[name-defined]
            except Exception:
                pass

    raise ValueError(f"Could not read CSV {path}: {last_error}")


def first_non_empty(row: dict[str, Any], keys: tuple[str, ...]) -> str | None:
    for key in keys:
        value = row.get(key)
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return None


def normalize_airport_code(raw: str | None) -> str | None:
    if raw is None:
        return None
    token = raw.strip().upper()
    if not token:
        return None
    # Accept ICAO-like US form (e.g. KLAX) by dropping leading K.
    if len(token) == 4 and token.startswith("K") and token[1:].isalpha():
        token = token[1:]
    if len(token) == 3 and token.isalpha():
        return token
    return None


def parse_price(raw: str | None) -> float | None:
    if raw is None:
        return None
    match = PRICE_RE.search(raw)
    if not match:
        return None
    try:
        return round(float(match.group(0).replace(",", "")), 2)
    except ValueError:
        return None


def load_airport_city_map(path: Path | None) -> dict[str, str]:
    mapping = dict(DEFAULT_AIRPORT_TO_CITY)
    if path is None:
        return mapping

    with path.open("r", encoding="utf-8") as fh:
        payload = json.load(fh)

    loaded = 0
    if isinstance(payload, dict):
        items = payload.items()
    elif isinstance(payload, list):
        items = []
        for row in payload:
            if not isinstance(row, dict):
                continue
            code = row.get("airport_code") or row.get("iata") or row.get("code")
            city = row.get("city")
            items.append((code, city))
    else:
        raise ValueError("airport-city map must be either a JSON object or array of objects")

    for code_raw, city_raw in items:
        code = normalize_airport_code(str(code_raw) if code_raw is not None else None)
        city = str(city_raw).strip() if city_raw is not None else ""
        if code and city:
            mapping[code] = city
            loaded += 1

    log(f"Loaded {loaded} airport→city overrides from {path}")
    return mapping


def read_hotel_prices(path: Path, airport_to_city: dict[str, str]) -> list[dict[str, Any]]:
    """Read hotel average-price rows and return lodging records.

    Output rows always contain city + nightly_rate, and preserve airport_code
    when an airport-derived row includes it.
    """
    reader, fh = open_csv_with_fallback(path)
    rows: list[dict[str, Any]] = []
    skipped_missing_price = 0
    skipped_missing_location = 0
    skipped_unknown_airport = 0

    try:
        for row in reader:
            city = first_non_empty(row, CITY_COLUMNS)
            airport_code = normalize_airport_code(first_non_empty(row, AIRPORT_COLUMNS))
            nightly_rate = parse_price(first_non_empty(row, PRICE_COLUMNS))

            if nightly_rate is None:
                skipped_missing_price += 1
                continue

            if not city and airport_code:
                city = airport_to_city.get(airport_code)
                if city is None:
                    skipped_unknown_airport += 1
                    continue
            elif not city:
                skipped_missing_location += 1
                continue

            rows.append(
                {
                    "city": city,
                    "nightly_rate": nightly_rate,
                    "airport_code": airport_code,
                }
            )
    finally:
        fh.close()

    skipped_total = skipped_missing_price + skipped_missing_location + skipped_unknown_airport
    log(
        "Read "
        f"{len(rows)} rows from {path.name} "
        f"(skipped {skipped_total}: missing_price={skipped_missing_price}, "
        f"missing_location={skipped_missing_location}, unknown_airport={skipped_unknown_airport})"
    )
    return rows


def write_output(
    rows: list[dict[str, Any]],
    output_path: Path,
    output_format: str,
    include_id: bool,
    id_start: int,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    include_airport_code = any(row.get("airport_code") for row in rows)

    if include_id:
        fields = ["id", "city", "nightly_rate"]
    else:
        fields = ["city", "nightly_rate"]

    if include_airport_code:
        fields.append("airport_code")

    records: list[dict[str, Any]] = []
    for idx, row in enumerate(rows, start=id_start):
        record: dict[str, Any] = {
            "city": row["city"],
            "nightly_rate": row["nightly_rate"],
        }
        if include_id:
            record["id"] = idx
        if include_airport_code:
            record["airport_code"] = row.get("airport_code")
        records.append(record)

    if output_format == "json":
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(records, fh, indent=2, ensure_ascii=False)
        return

    if output_format == "csv":
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fields)
            writer.writeheader()
            writer.writerows(records)
        return

    raise ValueError(f"Unsupported output format: {output_format}")


def infer_output_format(output_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    if output_path.suffix.lower() == ".json":
        return "json"
    return "csv"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Format hotel average prices into lodging rows (city, nightly_rate)."
    )
    parser.add_argument("--input", required=True, help="Path to us_city_hotel_average_prices.csv")
    parser.add_argument("--output", required=True, help="Output file path (.csv or .json)")
    parser.add_argument("--format", choices=("csv", "json"), default=None, help="Output format override")
    parser.add_argument(
        "--airport-city-map",
        default=None,
        help=(
            "Optional JSON mapping for airport-code inputs. "
            "Accepts {\"LAX\":\"Los Angeles\"} or [{\"airport_code\":\"LAX\",\"city\":\"Los Angeles\"}]."
        ),
    )
    parser.add_argument("--include-id", action="store_true", help="Include deterministic id column")
    parser.add_argument("--id-start", type=int, default=1, help="Starting id when --include-id is used")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    log(f"Starting lodging formatter (input={input_path}, output={output_path})")

    if not input_path.exists():
        print(f"Input file not found: {input_path}", file=sys.stderr)
        return 2

    try:
        airport_city_map_path = Path(args.airport_city_map).expanduser().resolve() if args.airport_city_map else None
        if airport_city_map_path and not airport_city_map_path.exists():
            print(f"Airport-city map not found: {airport_city_map_path}", file=sys.stderr)
            return 2

        airport_to_city = load_airport_city_map(airport_city_map_path)
        rows = read_hotel_prices(input_path, airport_to_city)
    except Exception as exc:
        print(f"Failed reading input file: {exc}", file=sys.stderr)
        return 1

    if not rows:
        print("No lodging rows generated.", file=sys.stderr)
        return 1

    # Sort by city name for consistent output
    rows.sort(key=lambda r: str(r["city"]).casefold())

    try:
        output_format = infer_output_format(output_path, args.format)
        write_output(
            rows=rows,
            output_path=output_path,
            output_format=output_format,
            include_id=args.include_id,
            id_start=args.id_start,
        )
    except Exception as exc:
        print(f"Failed writing output: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {len(rows)} lodging rows to {output_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
