#!/usr/bin/env python3
"""Normalize and deduplicate scraped hackathon data for Supabase events table.

Input row shape (from current scrapers):
  - name
  - city
  - start_datetime
  - end_datetime
  - total_prize
  - website

Output row shape:
  - source
  - name
  - city
  - country
  - start_datetime_utc
  - end_datetime_utc
  - in_person
  - prize_pool
  - url

`id` is intentionally omitted because the Supabase table defines
`id bigint generated by default as identity`.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse, urlunparse

DEFAULT_OUTPUT_FIELDS = [
    "source",
    "name",
    "city",
    "country",
    "start_datetime_utc",
    "end_datetime_utc",
    "in_person",
    "prize_pool",
    "url",
]

SPACE_RE = re.compile(r"\s+")
NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")
NUMBER_RE = re.compile(r"(?<!\d)(\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)([kKmM]?)(?!\d)")
ONLINE_RE = re.compile(r"\b(online|virtual|remote|worldwide|global)\b", re.IGNORECASE)

COUNTRY_ALIASES = {
    "US": "United States",
    "USA": "United States",
    "UNITED STATES": "United States",
    "UNITED STATES OF AMERICA": "United States",
    "UK": "United Kingdom",
    "U.K.": "United Kingdom",
    "UNITED KINGDOM": "United Kingdom",
    "ENGLAND": "United Kingdom",
    "SCOTLAND": "United Kingdom",
    "WALES": "United Kingdom",
    "IRELAND": "Ireland",
    "CANADA": "Canada",
    "CA": "Canada",
    "AU": "Australia",
    "AUS": "Australia",
    "AUSTRALIA": "Australia",
    "NZ": "New Zealand",
    "NEW ZEALAND": "New Zealand",
    "IN": "India",
    "INDIA": "India",
    "SG": "Singapore",
    "SINGAPORE": "Singapore",
    "MX": "Mexico",
    "MEXICO": "Mexico",
    "DE": "Germany",
    "GERMANY": "Germany",
    "FR": "France",
    "FRANCE": "France",
    "ES": "Spain",
    "SPAIN": "Spain",
    "JP": "Japan",
    "JAPAN": "Japan",
    "KR": "South Korea",
    "SOUTH KOREA": "South Korea",
    "CHINA": "China",
    "CN": "China",
    "BRAZIL": "Brazil",
    "BR": "Brazil",
}

US_STATE_CODES = {
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "DC",
}

US_STATE_NAMES = {
    "ALABAMA",
    "ALASKA",
    "ARIZONA",
    "ARKANSAS",
    "CALIFORNIA",
    "COLORADO",
    "CONNECTICUT",
    "DELAWARE",
    "FLORIDA",
    "GEORGIA",
    "HAWAII",
    "IDAHO",
    "ILLINOIS",
    "INDIANA",
    "IOWA",
    "KANSAS",
    "KENTUCKY",
    "LOUISIANA",
    "MAINE",
    "MARYLAND",
    "MASSACHUSETTS",
    "MICHIGAN",
    "MINNESOTA",
    "MISSISSIPPI",
    "MISSOURI",
    "MONTANA",
    "NEBRASKA",
    "NEVADA",
    "NEW HAMPSHIRE",
    "NEW JERSEY",
    "NEW MEXICO",
    "NEW YORK",
    "NORTH CAROLINA",
    "NORTH DAKOTA",
    "OHIO",
    "OKLAHOMA",
    "OREGON",
    "PENNSYLVANIA",
    "RHODE ISLAND",
    "SOUTH CAROLINA",
    "SOUTH DAKOTA",
    "TENNESSEE",
    "TEXAS",
    "UTAH",
    "VERMONT",
    "VIRGINIA",
    "WASHINGTON",
    "WEST VIRGINIA",
    "WISCONSIN",
    "WYOMING",
}


def normalize_space(value: str | None) -> str | None:
    if value is None:
        return None
    cleaned = SPACE_RE.sub(" ", str(value)).strip()
    return cleaned or None


def normalize_url(value: str | None) -> str | None:
    text = normalize_space(value)
    if not text:
        return None

    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", text):
        text = f"https://{text}"

    parsed = urlparse(text)
    scheme = (parsed.scheme or "https").lower()
    host = (parsed.netloc or "").lower().strip()

    if not host and parsed.path:
        # Handles inputs like "example.com/path" after adding scheme.
        reparsed = urlparse(f"https://{text}")
        scheme = reparsed.scheme
        host = reparsed.netloc.lower().strip()
        path = reparsed.path
    else:
        path = parsed.path

    if host.startswith("www."):
        host = host[4:]

    if not host:
        return None

    clean_path = re.sub(r"/{2,}", "/", path or "/")
    if clean_path != "/":
        clean_path = clean_path.rstrip("/")
    return urlunparse((scheme, host, clean_path, "", "", ""))


def parse_isoish_datetime(value: Any) -> datetime | None:
    text = normalize_space(None if value is None else str(value))
    if not text:
        return None

    candidate = text.replace("Z", "+00:00")
    candidate = candidate.replace(" ", "T", 1) if "T" not in candidate and " " in candidate else candidate

    try:
        return datetime.fromisoformat(candidate)
    except ValueError:
        pass

    for fmt in (
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%m/%d/%Y %H:%M:%S",
    ):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue
    return None


def to_utc_timestamp(value: Any) -> str | None:
    dt = parse_isoish_datetime(value)
    if not dt:
        return None
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def parse_prize_pool(value: Any) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return int(round(float(value)))

    text = normalize_space(str(value))
    if not text:
        return None

    amounts: list[float] = []
    for number, suffix in NUMBER_RE.findall(text):
        base = float(number.replace(",", ""))
        if suffix.lower() == "k":
            base *= 1_000
        elif suffix.lower() == "m":
            base *= 1_000_000
        amounts.append(base)

    if not amounts:
        return None
    return int(round(max(amounts)))


def normalize_name_key(name: str | None) -> str | None:
    text = normalize_space(name)
    if not text:
        return None
    lowered = text.casefold().replace("&", " and ")
    lowered = NON_ALNUM_RE.sub(" ", lowered).strip()
    if not lowered:
        return None
    tokens = [token for token in lowered.split() if token not in {"the", "a", "an"}]
    return " ".join(tokens) if tokens else None


def infer_country(parts: list[str]) -> str | None:
    if not parts:
        return None

    upper_parts = [part.strip().upper().rstrip(".") for part in parts if part.strip()]
    if not upper_parts:
        return None

    if any(token in US_STATE_CODES or token in US_STATE_NAMES for token in upper_parts[1:]):
        return "United States"

    last = upper_parts[-1]
    if last in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[last]

    if len(last) == 2 and last.isalpha() and last in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[last]

    return None


def parse_city_country_in_person(raw_city: str | None) -> tuple[str | None, str | None, bool | None]:
    city_text = normalize_space(raw_city)
    if not city_text:
        return None, None, None

    if ONLINE_RE.search(city_text):
        return None, None, False

    parts = [part.strip(" -") for part in city_text.split(",")]
    parts = [part for part in parts if part]
    if not parts:
        return None, None, None

    country = infer_country(parts)
    city = normalize_space(parts[0])

    if len(parts) == 1:
        token = parts[0].upper().rstrip(".")
        if token in COUNTRY_ALIASES:
            return None, COUNTRY_ALIASES[token], None

    return city, country, True


def choose_text(preferred: str | None, candidate: str | None) -> str | None:
    if not preferred:
        return candidate
    if not candidate:
        return preferred
    return candidate if len(candidate) > len(preferred) else preferred


def parse_output_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        return None


def has_precise_start_time(value: str | None) -> bool:
    dt = parse_output_datetime(value)
    if not dt:
        return False
    return dt.time().isoformat() != "00:00:00"


def has_precise_end_time(value: str | None) -> bool:
    dt = parse_output_datetime(value)
    if not dt:
        return False
    return dt.time().isoformat() != "23:59:59"


def choose_start_datetime(left: str | None, right: str | None) -> str | None:
    if not left:
        return right
    if not right:
        return left

    left_precise = has_precise_start_time(left)
    right_precise = has_precise_start_time(right)
    if left_precise != right_precise:
        return right if right_precise else left

    left_dt = parse_output_datetime(left)
    right_dt = parse_output_datetime(right)
    if left_dt and right_dt:
        return left if left_dt <= right_dt else right
    return choose_text(left, right)


def choose_end_datetime(left: str | None, right: str | None) -> str | None:
    if not left:
        return right
    if not right:
        return left

    left_precise = has_precise_end_time(left)
    right_precise = has_precise_end_time(right)
    if left_precise != right_precise:
        return right if right_precise else left

    left_dt = parse_output_datetime(left)
    right_dt = parse_output_datetime(right)
    if left_dt and right_dt:
        return left if left_dt >= right_dt else right
    return choose_text(left, right)


def choose_in_person(left: bool | None, right: bool | None) -> bool | None:
    values = [value for value in (left, right) if value is not None]
    if not values:
        return None
    if all(value == values[0] for value in values):
        return values[0]
    return None


def url_rank(url: str | None) -> tuple[int, int]:
    if not url:
        return (-10, 0)
    host = urlparse(url).netloc
    rank = 0
    if "devpost.com" in host:
        rank -= 2
    if "mlh" in host:
        rank -= 1
    if urlparse(url).path not in {"", "/"}:
        rank += 1
    return (rank, len(url))


def merge_records(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    merged = dict(left)

    merged["name"] = choose_text(left.get("name"), right.get("name"))
    merged["city"] = choose_text(left.get("city"), right.get("city"))
    merged["country"] = choose_text(left.get("country"), right.get("country"))
    merged["start_datetime_utc"] = choose_start_datetime(
        left.get("start_datetime_utc"), right.get("start_datetime_utc")
    )
    merged["end_datetime_utc"] = choose_end_datetime(
        left.get("end_datetime_utc"), right.get("end_datetime_utc")
    )
    merged["in_person"] = choose_in_person(left.get("in_person"), right.get("in_person"))

    left_prize = left.get("prize_pool")
    right_prize = right.get("prize_pool")
    if left_prize is None:
        merged["prize_pool"] = right_prize
    elif right_prize is None:
        merged["prize_pool"] = left_prize
    else:
        merged["prize_pool"] = max(int(left_prize), int(right_prize))

    left_url = left.get("url")
    right_url = right.get("url")
    merged["url"] = right_url if url_rank(right_url) > url_rank(left_url) else left_url

    sources = set(left.get("_sources", set()))
    sources.update(right.get("_sources", set()))
    merged["_sources"] = sources
    merged["source"] = ",".join(sorted(sources)) if sources else (left.get("source") or right.get("source") or "mlh")
    return merged


def normalize_scraped_row(row: dict[str, Any], source: str) -> dict[str, Any] | None:
    name = normalize_space(row.get("name"))
    raw_city = normalize_space(row.get("city"))
    start_raw = row.get("start_datetime", row.get("start_datetime_utc"))
    end_raw = row.get("end_datetime", row.get("end_datetime_utc"))
    prize_raw = row.get("total_prize", row.get("prize_pool"))
    url_raw = row.get("website", row.get("url"))

    url = normalize_url(url_raw)
    if not name and not url:
        return None

    city, country, in_person = parse_city_country_in_person(raw_city)

    normalized: dict[str, Any] = {
        "source": source,
        "name": name,
        "city": city,
        "country": country,
        "start_datetime_utc": to_utc_timestamp(start_raw),
        "end_datetime_utc": to_utc_timestamp(end_raw),
        "in_person": in_person,
        "prize_pool": parse_prize_pool(prize_raw),
        "url": url,
        "_sources": {source},
    }

    if normalized["start_datetime_utc"] and normalized["end_datetime_utc"]:
        start_dt = parse_output_datetime(normalized["start_datetime_utc"])
        end_dt = parse_output_datetime(normalized["end_datetime_utc"])
        if start_dt and end_dt and end_dt < start_dt:
            normalized["start_datetime_utc"], normalized["end_datetime_utc"] = (
                normalized["end_datetime_utc"],
                normalized["start_datetime_utc"],
            )

    return normalized


def read_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    suffix = path.suffix.lower()
    if suffix == ".json":
        with path.open("r", encoding="utf-8") as fh:
            payload = json.load(fh)
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, dict)]
        if isinstance(payload, dict):
            for key in ("records", "events", "hackathons", "data"):
                value = payload.get(key)
                if isinstance(value, list):
                    return [item for item in value if isinstance(item, dict)]
            return [payload]
        raise ValueError(f"Unsupported JSON payload in {path}")

    if suffix == ".csv":
        with path.open("r", encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            return [dict(row) for row in reader]

    raise ValueError(f"Unsupported file extension for {path}")


def load_normalized_records(paths: list[Path], source: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in paths:
        for row in read_rows(path):
            normalized = normalize_scraped_row(row, source)
            if normalized:
                records.append(normalized)
    return records


def merge_by_url(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: "OrderedDict[str, dict[str, Any]]" = OrderedDict()
    passthrough: list[dict[str, Any]] = []

    for record in records:
        key = record.get("url")
        if not key:
            passthrough.append(record)
            continue
        if key in grouped:
            grouped[key] = merge_records(grouped[key], record)
        else:
            grouped[key] = record

    return list(grouped.values()) + passthrough


def merge_by_name_start(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: "OrderedDict[tuple[str, str], dict[str, Any]]" = OrderedDict()
    passthrough: list[dict[str, Any]] = []

    for record in records:
        name_key = normalize_name_key(record.get("name"))
        start = record.get("start_datetime_utc")
        start_date = start[:10] if isinstance(start, str) and len(start) >= 10 else None
        if not name_key or not start_date:
            passthrough.append(record)
            continue

        key = (name_key, start_date)
        if key in grouped:
            grouped[key] = merge_records(grouped[key], record)
        else:
            grouped[key] = record

    return list(grouped.values()) + passthrough


def strip_internal_fields(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for record in records:
        cleaned.append({field: record.get(field) for field in DEFAULT_OUTPUT_FIELDS})
    return cleaned


def infer_output_format(output_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    return "csv" if output_path.suffix.lower() == ".csv" else "json"


def write_output(records: list[dict[str, Any]], output_path: Path, output_format: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_format == "json":
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(records, fh, indent=2, ensure_ascii=False)
        return

    if output_format == "csv":
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=DEFAULT_OUTPUT_FIELDS)
            writer.writeheader()
            writer.writerows(records)
        return

    raise ValueError(f"Unsupported output format: {output_format}")


def discover_default_inputs(repo_root: Path) -> tuple[list[Path], list[Path]]:
    mlh_patterns = [
        "MLH-Scraper/mlh*.json",
        "MLH-Scraper/mlh*.csv",
        "mlh*.json",
        "mlh*.csv",
    ]
    devpost_patterns = [
        "Devpost-Scraper/devpost*.json",
        "Devpost-Scraper/devpost*.csv",
        "devpost*.json",
        "devpost*.csv",
    ]

    mlh_files: list[Path] = []
    devpost_files: list[Path] = []

    for pattern in mlh_patterns:
        mlh_files.extend(sorted(repo_root.glob(pattern)))
    for pattern in devpost_patterns:
        devpost_files.extend(sorted(repo_root.glob(pattern)))

    # Preserve order while removing duplicates.
    mlh_unique = list(dict.fromkeys(path.resolve() for path in mlh_files))
    devpost_unique = list(dict.fromkeys(path.resolve() for path in devpost_files))
    return mlh_unique, devpost_unique


def parse_args(argv: list[str]) -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Clean MLH/Devpost scraped data for Supabase events ingestion."
    )
    parser.add_argument("--mlh", nargs="*", default=None, help="MLH input files (JSON or CSV)")
    parser.add_argument("--devpost", nargs="*", default=None, help="Devpost input files (JSON or CSV)")
    parser.add_argument(
        "--output",
        default=str(script_dir / "cleaned_events.json"),
        help="Output file path (JSON or CSV)",
    )
    parser.add_argument("--format", choices=("json", "csv"), default=None, help="Output format override")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    output_path = Path(args.output).expanduser().resolve()

    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent

    if args.mlh is None and args.devpost is None:
        mlh_files, devpost_files = discover_default_inputs(repo_root)
    else:
        mlh_files = [Path(path).expanduser().resolve() for path in (args.mlh or [])]
        devpost_files = [Path(path).expanduser().resolve() for path in (args.devpost or [])]

    if not mlh_files and not devpost_files:
        print(
            "No input files found. Provide --mlh/--devpost paths or place scraper outputs in MLH-Scraper/ and Devpost-Scraper/.",
            file=sys.stderr,
        )
        return 2

    try:
        records = []
        records.extend(load_normalized_records(mlh_files, "mlh"))
        records.extend(load_normalized_records(devpost_files, "devpost"))
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as exc:
        print(f"Failed to read input files: {exc}", file=sys.stderr)
        return 1

    if not records:
        print("No valid records found in input files.", file=sys.stderr)
        return 1

    merged = merge_by_url(records)
    merged = merge_by_name_start(merged)

    merged.sort(key=lambda row: ((row.get("start_datetime_utc") or ""), (row.get("name") or "").casefold()))
    cleaned = strip_internal_fields(merged)

    output_format = infer_output_format(output_path, args.format)
    write_output(cleaned, output_path, output_format)

    print(
        f"Wrote {len(cleaned)} cleaned events to {output_path} "
        f"(from {len(records)} raw rows, removed {len(records) - len(cleaned)} duplicates)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
