#!/usr/bin/env python3
"""Format Booking + Tripadvisor hotel CSVs into rows for public.lodging.

Target schema:
  id bigint generated by default as identity not null,
  city text,
  nightly_rate real

By default, this script outputs only `city` + `nightly_rate` because `id` is
identity-generated by Postgres. Use --include-id if you want deterministic ids
in output files.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

SPACE_RE = re.compile(r"\s+")
PRICE_RE = re.compile(r"-?\d+(?:,\d{3})*(?:\.\d+)?")
RANK_PREFIX_RE = re.compile(r"^\d+\.\s*")
NON_ALNUM_SPACE_RE = re.compile(r"[^a-z0-9]+")

# Extra aliases helpful for Tripadvisor property-name-based city inference.
MANUAL_CITY_ALIASES: dict[str, str] = {
    "samui": "Koh Samui",
    "koh samui": "Koh Samui",
    "ao nang": "Ao Nang Beach",
    "khao lak": "Khao Lak",
    "ko lanta": "Ko Lanta",
    "koh lanta": "Ko Lanta",
    "ko tao": "Ko Tao",
    "koh tao": "Ko Tao",
    "phi phi": "Phi Phi Islands",
    "phuket": "Phuket",
    "krabi": "Krabi",
    "bangkok": "Bangkok",
    "chiang mai": "Chiang Mai",
    "hua hin": "Hua Hin",
    "pattaya": "Pattaya",
    "patong": "Patong Beach",
    "karon": "Karon Beach",
    "kamala": "Kamala Beach",
    "rawai": "Rawai Beach",
    "chaweng": "Chaweng",
    "bophut": "Bophut",
    "mae nam": "Mae Nam",
}


@dataclass
class RunningStats:
    count: int = 0
    total_rate: float = 0.0

    def add(self, nightly_rate: float) -> None:
        self.count += 1
        self.total_rate += nightly_rate

    def avg_rate(self) -> float | None:
        if self.count == 0:
            return None
        return round(self.total_rate / self.count, 2)


def normalize_space(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).replace("\xa0", " ")
    text = SPACE_RE.sub(" ", text).strip(" ,")
    return text or None


def normalize_city(value: str | None) -> str | None:
    text = normalize_space(value)
    if not text:
        return None
    # Normalize odd comma spacing, e.g. "City Center , Chaweng".
    text = re.sub(r"\s*,\s*", ", ", text)
    return text.strip(" ,") or None


def parse_price(value: Any) -> float | None:
    text = normalize_space(value)
    if not text:
        return None
    match = PRICE_RE.search(text)
    if not match:
        return None
    try:
        return float(match.group(0).replace(",", ""))
    except ValueError:
        return None


def open_csv_with_fallback(path: Path) -> tuple[csv.DictReader, Any]:
    encodings = ("utf-8-sig", "utf-8", "cp1252", "latin-1")
    last_error: Exception | None = None

    for encoding in encodings:
        try:
            fh = path.open("r", encoding=encoding, newline="")
            reader = csv.DictReader(fh)
            # Force header decode/read now.
            _ = reader.fieldnames
            return reader, fh
        except Exception as exc:
            last_error = exc
            try:
                fh.close()  # type: ignore[name-defined]
            except Exception:
                pass

    raise ValueError(f"Could not read CSV {path}: {last_error}")


def extract_city_from_booking_location(location: Any) -> str | None:
    text = normalize_city(normalize_space(location))
    if not text:
        return None

    parts = [normalize_city(part) for part in text.split(",")]
    parts = [part for part in parts if part]
    if parts:
        return parts[-1]
    return text


def clean_tripadvisor_name(name: Any) -> str | None:
    text = normalize_space(name)
    if not text:
        return None
    return normalize_space(RANK_PREFIX_RE.sub("", text))


def phrase_key(text: str) -> str:
    return NON_ALNUM_SPACE_RE.sub(" ", text.casefold()).strip()


def build_city_alias_map(booking_cities: Iterable[str]) -> dict[str, str]:
    alias_to_city: dict[str, str] = {}

    def add_alias(alias: str, canonical_city: str) -> None:
        key = phrase_key(alias)
        if not key:
            return
        if key not in alias_to_city:
            alias_to_city[key] = canonical_city

    for city in sorted(set(booking_cities), key=lambda item: (-len(item), item.casefold())):
        canonical = city
        lower = city.casefold()
        add_alias(city, canonical)

        if lower.startswith("koh "):
            add_alias(city[4:], canonical)
        if lower.startswith("ko "):
            add_alias(city[3:], canonical)
        if lower.endswith(" beach"):
            add_alias(city[:-6], canonical)
        if lower.endswith(" city center"):
            add_alias(city[:-12], canonical)

    for alias, canonical in MANUAL_CITY_ALIASES.items():
        add_alias(alias, canonical)

    return alias_to_city


def extract_city_from_tripadvisor_name(name: Any, alias_map: dict[str, str]) -> str | None:
    clean_name = clean_tripadvisor_name(name)
    if not clean_name:
        return None

    normalized = f" {phrase_key(clean_name)} "
    # Longest aliases first to avoid short-token overmatches.
    aliases = sorted(alias_map.items(), key=lambda kv: len(kv[0]), reverse=True)
    for alias_key, canonical in aliases:
        if f" {alias_key} " in normalized:
            return canonical

    return None


def read_booking_rows(path: Path) -> tuple[list[tuple[str, float]], int]:
    reader, fh = open_csv_with_fallback(path)
    kept: list[tuple[str, float]] = []
    skipped = 0

    try:
        for row in reader:
            city = extract_city_from_booking_location(row.get("Location"))
            nightly_rate = parse_price(row.get("Room Price (in BDT or any other currency)"))
            if city is None or nightly_rate is None:
                skipped += 1
                continue
            kept.append((city, nightly_rate))
    finally:
        fh.close()

    return kept, skipped


def read_tripadvisor_rows(path: Path, alias_map: dict[str, str]) -> tuple[list[tuple[str, float]], int]:
    reader, fh = open_csv_with_fallback(path)
    kept: list[tuple[str, float]] = []
    skipped = 0

    try:
        for row in reader:
            city = extract_city_from_tripadvisor_name(row.get("property name "), alias_map)
            nightly_rate = parse_price(row.get("Room Price (in BDT or any other currency)"))
            if city is None or nightly_rate is None:
                skipped += 1
                continue
            kept.append((city, nightly_rate))
    finally:
        fh.close()

    return kept, skipped


def aggregate_city_rates(rows: list[tuple[str, float]]) -> list[tuple[str, float, int]]:
    stats: dict[str, RunningStats] = {}
    for city, rate in rows:
        key = normalize_city(city)
        if key is None:
            continue
        if key not in stats:
            stats[key] = RunningStats()
        stats[key].add(rate)

    result: list[tuple[str, float, int]] = []
    for city in sorted(stats, key=lambda item: item.casefold()):
        avg_rate = stats[city].avg_rate()
        if avg_rate is None:
            continue
        result.append((city, avg_rate, stats[city].count))
    return result


def write_output(
    aggregated: list[tuple[str, float, int]],
    output_path: Path,
    output_format: str,
    include_id: bool,
    id_start: int,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if include_id:
        fields = ["id", "city", "nightly_rate"]
    else:
        fields = ["city", "nightly_rate"]

    rows: list[dict[str, Any]] = []
    for idx, (city, avg_rate, _count) in enumerate(aggregated, start=id_start):
        row: dict[str, Any] = {"city": city, "nightly_rate": avg_rate}
        if include_id:
            row["id"] = idx
        rows.append(row)

    if output_format == "json":
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(rows, fh, indent=2, ensure_ascii=False)
        return

    if output_format == "csv":
        with output_path.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)
        return

    raise ValueError(f"Unsupported output format: {output_format}")


def infer_output_format(output_path: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    if output_path.suffix.lower() == ".json":
        return "json"
    return "csv"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Format hotel datasets into aggregated lodging rows (city, nightly_rate)."
    )
    parser.add_argument("--booking", required=True, help="Path to booking_hotel.csv")
    parser.add_argument("--tripadvisor", required=True, help="Path to tripadvisor_room.csv")
    parser.add_argument("--output", required=True, help="Output file path (.csv or .json)")
    parser.add_argument("--format", choices=("csv", "json"), default=None, help="Output format override")
    parser.add_argument("--include-id", action="store_true", help="Include deterministic id column")
    parser.add_argument("--id-start", type=int, default=1, help="Starting id when --include-id is used")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    booking_path = Path(args.booking).expanduser().resolve()
    tripadvisor_path = Path(args.tripadvisor).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    if not booking_path.exists():
        print(f"Booking file not found: {booking_path}", file=sys.stderr)
        return 2
    if not tripadvisor_path.exists():
        print(f"Tripadvisor file not found: {tripadvisor_path}", file=sys.stderr)
        return 2

    try:
        booking_rows, skipped_booking = read_booking_rows(booking_path)
    except Exception as exc:
        print(f"Failed reading booking file: {exc}", file=sys.stderr)
        return 1

    booking_cities = [city for city, _rate in booking_rows]
    alias_map = build_city_alias_map(booking_cities)

    try:
        trip_rows, skipped_tripadvisor = read_tripadvisor_rows(tripadvisor_path, alias_map)
    except Exception as exc:
        print(f"Failed reading tripadvisor file: {exc}", file=sys.stderr)
        return 1

    combined = booking_rows + trip_rows
    aggregated = aggregate_city_rates(combined)

    if not aggregated:
        print("No lodging rows generated.", file=sys.stderr)
        return 1

    try:
        output_format = infer_output_format(output_path, args.format)
        write_output(
            aggregated=aggregated,
            output_path=output_path,
            output_format=output_format,
            include_id=args.include_id,
            id_start=args.id_start,
        )
    except Exception as exc:
        print(f"Failed writing output: {exc}", file=sys.stderr)
        return 1

    print(
        f"Wrote {len(aggregated)} lodging rows to {output_path} "
        f"(booking kept={len(booking_rows)}, booking skipped={skipped_booking}, "
        f"tripadvisor kept={len(trip_rows)}, tripadvisor skipped={skipped_tripadvisor})."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
